let editingId=null;const $=id=>document.getElementById(id);let content=null;
const defaults={identity:{name:"Sadaf Ali",role:"Data Analyst",availability:"Available for opportunities",heroEyebrow:"DATA ANALYST · PYTHON · SQL · POWER BI",heroTitleLine1:"Turning data",heroTitleLine2:"into decisions.",heroLead:"I analyze data, uncover patterns, and build clear analytical solutions that help people make better decisions.",linkedin:"",github:"",email:"",resumeUrl:"resume.pdf",heroQuote:"Knowledge itself is power.",heroQuoteAuthor:"Francis Bacon"},about:{eyebrow:"01 / ABOUT",headingLine1:"Curious about the",headingLine2:"story behind data.",text:"",stats:[]},skills:{eyebrow:"02 / SKILLS",headingLine1:"Tools I use to",headingLine2:"solve problems.",groups:[]},experience:{eyebrow:"03 / EXPERIENCE",headingLine1:"Where I've",headingLine2:"worked.",items:[]},projects:{eyebrow:"04 / PROJECTS",headingLine1:"Selected",headingLine2:"work.",intro:"Projects are managed from the private admin dashboard."},education:{eyebrow:"05 / EDUCATION",headingLine1:"Academic",headingLine2:"foundation.",items:[]},contact:{eyebrow:"06 / CONTACT",headingLine1:"Let's build something",headingLine2:"meaningful.",text:"",buttonLabel:"Start a conversation"},footer:{tagline:"SA. — Data Analyst",copyright:"All rights reserved."}};
function clone(x){return JSON.parse(JSON.stringify(x))} function merge(a,b){if(Array.isArray(a)||Array.isArray(b))return b??a;if(a&&typeof a==='object'&&b&&typeof b==='object')return Object.keys({...a,...b}).reduce((o,k)=>{o[k]=merge(a[k],b[k]);return o},{});return b??a}
async function boot(){const {data:{session}}=await supabaseClient.auth.getSession();if(!session){$("loginView").classList.remove("hidden");return}$("adminView").classList.remove("hidden");await loadContent();await loadProjects()}
async function loadContent(){const {data,error}=await supabaseClient.from('site_content').select('content').eq('id',1).maybeSingle();content=merge(clone(defaults),data?.content||{});if(error){console.error(error);alert('Could not load website content: '+error.message)}renderContent()}
function val(id,v){$(id).value=v??''}
function renderContent(){const i=content.identity,a=content.about,s=content.skills,e=content.experience,pr=content.projects,ed=content.education,co=content.contact,f=content.footer;val('cName',i.name);val('cRole',i.role);val('cAvailability',i.availability);val('cHeroEyebrow',i.heroEyebrow);val('cHero1',i.heroTitleLine1);val('cHero2',i.heroTitleLine2);val('cHeroLead',i.heroLead);val('cEmail',i.email);val('cResume',i.resumeUrl);val('cLinkedin',i.linkedin);val('cGithub',i.github);val('cHeroQuote',i.heroQuote);val('cHeroQuoteAuthor',i.heroQuoteAuthor);val('aEyebrow',a.eyebrow);val('aH1',a.headingLine1);val('aH2',a.headingLine2);val('aText',a.text);renderStats();val('sEyebrow',s.eyebrow);val('sH1',s.headingLine1);val('sH2',s.headingLine2);renderSkills();val('eEyebrow',e.eyebrow);val('eH1',e.headingLine1);val('eH2',e.headingLine2);renderExperience();val('prEyebrow',pr.eyebrow);val('prH1',pr.headingLine1);val('prH2',pr.headingLine2);val('prIntro',pr.intro);val('edEyebrow',ed.eyebrow);val('edH1',ed.headingLine1);val('edH2',ed.headingLine2);renderEducation();val('coEyebrow',co.eyebrow);val('coH1',co.headingLine1);val('coH2',co.headingLine2);val('coText',co.text);val('coButton',co.buttonLabel);val('fTagline',f.tagline);val('fCopyright',f.copyright)}
function renderStats(){$('statsEditor').innerHTML=(content.about.stats||[]).map((x,i)=>`<div class="repeat-row"><input data-stat-v="${i}" value="${esc(x.value)}" placeholder="01"><input data-stat-l="${i}" value="${esc(x.label)}" placeholder="Data-first mindset"><button class="btn small danger" data-del-stat="${i}">Remove</button></div>`).join('');document.querySelectorAll('[data-del-stat]').forEach(b=>b.onclick=()=>{content.about.stats.splice(+b.dataset.delStat,1);renderStats()})}
function renderSkills(){$('skillsEditor').innerHTML=(content.skills.groups||[]).map((g,i)=>`<div class="repeat-card"><div class="repeat-head"><strong>Skill group ${i+1}</strong><button class="btn small danger" data-del-skill="${i}">Remove</button></div><label>Category<input data-skill-title="${i}" value="${esc(g.title)}"></label><label>Skills <small>comma separated</small><textarea data-skill-items="${i}" rows="3">${esc((g.items||[]).join(', '))}</textarea></label></div>`).join('');document.querySelectorAll('[data-del-skill]').forEach(b=>b.onclick=()=>{content.skills.groups.splice(+b.dataset.delSkill,1);renderSkills()})}
function renderExperience(){$('experienceEditor').innerHTML=(content.experience.items||[]).map((x,i)=>`<div class="repeat-card"><div class="repeat-head"><strong>Experience ${i+1}</strong><button class="btn small danger" data-del-exp="${i}">Remove</button></div><div class="form-grid"><label>Number<input data-exp-number="${i}" value="${esc(x.number)}"></label><label>Company<input data-exp-company="${i}" value="${esc(x.company)}"></label><label>Role<input data-exp-role="${i}" value="${esc(x.role)}"></label><label>Dates<input data-exp-period="${i}" value="${esc(x.period)}"></label></div><label>Description<textarea data-exp-desc="${i}" rows="4">${esc(x.description)}</textarea></div>`).join('');document.querySelectorAll('[data-del-exp]').forEach(b=>b.onclick=()=>{content.experience.items.splice(+b.dataset.delExp,1);renderExperience()})}
function renderEducation(){$('educationEditor').innerHTML=(content.education.items||[]).map((x,i)=>`<div class="repeat-card"><div class="repeat-head"><strong>Education ${i+1}</strong><button class="btn small danger" data-del-ed="${i}">Remove</button></div><div class="form-grid"><label>Degree<input data-ed-degree="${i}" value="${esc(x.degree)}"></label><label>Field<input data-ed-field="${i}" value="${esc(x.field)}"></label><label>Institution<input data-ed-inst="${i}" value="${esc(x.institution)}"></label><label>Location<input data-ed-location="${i}" value="${esc(x.location)}"></label><label>Dates<input data-ed-period="${i}" value="${esc(x.period)}"></label></div></div>`).join('');document.querySelectorAll('[data-del-ed]').forEach(b=>b.onclick=()=>{content.education.items.splice(+b.dataset.delEd,1);renderEducation()})}
function syncContent(){const i=content.identity,a=content.about,s=content.skills,e=content.experience,pr=content.projects,ed=content.education,co=content.contact,f=content.footer;[['cName','name'],['cRole','role'],['cAvailability','availability'],['cHeroEyebrow','heroEyebrow'],['cHero1','heroTitleLine1'],['cHero2','heroTitleLine2'],['cHeroLead','heroLead'],['cEmail','email'],['cResume','resumeUrl'],['cLinkedin','linkedin'],['cGithub','github'],['cHeroQuote','heroQuote'],['cHeroQuoteAuthor','heroQuoteAuthor']].forEach(([id,k])=>i[k]=$(id).value.trim());[['aEyebrow','eyebrow'],['aH1','headingLine1'],['aH2','headingLine2'],['aText','text']].forEach(([id,k])=>a[k]=$(id).value.trim());a.stats=(content.about.stats||[]).map((x,j)=>({value:document.querySelector(`[data-stat-v="${j}"]`)?.value.trim()||'',label:document.querySelector(`[data-stat-l="${j}"]`)?.value.trim()||''}));[['sEyebrow','eyebrow'],['sH1','headingLine1'],['sH2','headingLine2']].forEach(([id,k])=>s[k]=$(id).value.trim());s.groups=(content.skills.groups||[]).map((g,j)=>({title:document.querySelector(`[data-skill-title="${j}"]`)?.value.trim()||'',items:(document.querySelector(`[data-skill-items="${j}"]`)?.value||'').split(',').map(x=>x.trim()).filter(Boolean)}));[['eEyebrow','eyebrow'],['eH1','headingLine1'],['eH2','headingLine2']].forEach(([id,k])=>e[k]=$(id).value.trim());e.items=(content.experience.items||[]).map((x,j)=>({number:document.querySelector(`[data-exp-number="${j}"]`)?.value.trim()||'',company:document.querySelector(`[data-exp-company="${j}"]`)?.value.trim()||'',role:document.querySelector(`[data-exp-role="${j}"]`)?.value.trim()||'',period:document.querySelector(`[data-exp-period="${j}"]`)?.value.trim()||'',description:document.querySelector(`[data-exp-desc="${j}"]`)?.value.trim()||''}));[['prEyebrow','eyebrow'],['prH1','headingLine1'],['prH2','headingLine2'],['prIntro','intro']].forEach(([id,k])=>pr[k]=$(id).value.trim());[['edEyebrow','eyebrow'],['edH1','headingLine1'],['edH2','headingLine2']].forEach(([id,k])=>ed[k]=$(id).value.trim());ed.items=(content.education.items||[]).map((x,j)=>({degree:document.querySelector(`[data-ed-degree="${j}"]`)?.value.trim()||'',field:document.querySelector(`[data-ed-field="${j}"]`)?.value.trim()||'',institution:document.querySelector(`[data-ed-inst="${j}"]`)?.value.trim()||'',location:document.querySelector(`[data-ed-location="${j}"]`)?.value.trim()||'',period:document.querySelector(`[data-ed-period="${j}"]`)?.value.trim()||''}));[['coEyebrow','eyebrow'],['coH1','headingLine1'],['coH2','headingLine2'],['coText','text'],['coButton','buttonLabel']].forEach(([id,k])=>co[k]=$(id).value.trim());[['fTagline','tagline'],['fCopyright','copyright']].forEach(([id,k])=>f[k]=$(id).value.trim())}
async function saveContent(message='Saved ✓'){syncContent();const payload={id:1,content:clone(content),updated_at:new Date().toISOString()};const {error}=await supabaseClient.from('site_content').upsert(payload,{onConflict:'id'});if(error){console.error(error);alert('Could not save website content: '+error.message);return false}const b=$('saveContentBtn');const old=b.textContent;b.textContent=message;setTimeout(()=>b.textContent=old,1800);return true}
$('saveContentBtn').onclick=()=>saveContent('Saved ✓');
$('saveExperienceBtn')?.addEventListener('click',async()=>{syncContent();const ok=await saveContent('Experience saved ✓');if(ok) renderExperience()});
document.addEventListener('input',e=>{if(e.target.matches('[data-exp-number],[data-exp-company],[data-exp-role],[data-exp-period],[data-exp-desc]')) syncExperienceOnly()});
function syncExperienceOnly(){if(!content?.experience)return;content.experience.items=(content.experience.items||[]).map((x,j)=>({number:document.querySelector(`[data-exp-number="${j}"]`)?.value.trim()||'',company:document.querySelector(`[data-exp-company="${j}"]`)?.value.trim()||'',role:document.querySelector(`[data-exp-role="${j}"]`)?.value.trim()||'',period:document.querySelector(`[data-exp-period="${j}"]`)?.value.trim()||'',description:document.querySelector(`[data-exp-desc="${j}"]`)?.value.trim()||''}));}
async function saveAbout(){syncContent();const ok=await saveContent('About saved ✓');if(ok){renderStats();}}
async function saveSkills(){syncContent();const ok=await saveContent('Skills saved ✓');if(ok){renderSkills();}}
$('saveAboutBtn')?.addEventListener('click',saveAbout);
$('saveSkillsBtn')?.addEventListener('click',saveSkills);
async function saveEducation(){
  syncContent();
  const ok=await saveContent('Education saved ✓');
  if(ok)renderEducation();
}
$('saveEducationBtn')?.addEventListener('click',saveEducation);
function syncStats(){if(!content?.about)return;content.about.stats=(content.about.stats||[]).map((x,j)=>({value:document.querySelector(`[data-stat-v="${j}"]`)?.value.trim()||'',label:document.querySelector(`[data-stat-l="${j}"]`)?.value.trim()||''}));}function syncSkills(){if(!content?.skills)return;content.skills.groups=(content.skills.groups||[]).map((g,j)=>({title:document.querySelector(`[data-skill-title="${j}"]`)?.value.trim()||'',items:(document.querySelector(`[data-skill-items="${j}"]`)?.value||'').split(',').map(x=>x.trim()).filter(Boolean)}));}$('addStat').onclick=()=>{syncStats();content.about.stats.push({value:String(content.about.stats.length+1).padStart(2,'0'),label:'New stat'});renderStats()};$('addSkillGroup').onclick=()=>{syncSkills();content.skills.groups.push({title:'New skill group',items:[]});renderSkills()};$('addExperience').onclick=()=>{content.experience.items.push({number:String(content.experience.items.length+1).padStart(2,'0'),company:'Company',role:'Role',period:'Dates',description:'Description'});renderExperience()};function syncEducationOnly(){
  if(!content?.education)return;
  content.education.items=(content.education.items||[]).map((x,j)=>({
    degree:document.querySelector(`[data-ed-degree="${j}"]`)?.value.trim()||'',
    field:document.querySelector(`[data-ed-field="${j}"]`)?.value.trim()||'',
    institution:document.querySelector(`[data-ed-inst="${j}"]`)?.value.trim()||'',
    location:document.querySelector(`[data-ed-location="${j}"]`)?.value.trim()||'',
    period:document.querySelector(`[data-ed-period="${j}"]`)?.value.trim()||''
  }));
}
$('addEducation').onclick=()=>{
  syncEducationOnly();
  content.education.items.push({degree:'Degree',field:'Field',institution:'Institution',location:'Location',period:''});
  renderEducation();
};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab,.editor-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelector(`[data-panel="${t.dataset.tab}"]`).classList.add('active')});
async function loadProjects(){const {data,error}=await supabaseClient.from('projects').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:true});if(error){$('projectsAdmin').innerHTML=`<p class="error">${esc(error.message)}</p>`;return}$('projectsAdmin').innerHTML=data.length?data.map((p,i)=>`<div class="admin-project"><div class="admin-number">${String(i+1).padStart(2,'0')}</div><div class="admin-info"><span class="eyebrow">PROJECT ${i+1}</span><h3>${esc(p.title)}</h3><p>${esc(p.subtitle||'No subtitle')}</p></div><div class="admin-actions"><button class="btn small" onclick='editProject(${JSON.stringify(p).replace(/'/g,'&#39;')})'>Edit</button><button class="btn small danger" onclick="removeProject(${p.id})">Delete</button></div></div>`).join(''):`<div class="empty"><strong>No projects yet.</strong><br>Click “+ Add project” to create your first one.</div>`}
window.editProject=p=>{editingId=p.id;$('modalEyebrow').textContent='EDIT PROJECT';$('modalTitle').textContent='Edit project';fill(p);open()};function fill(p){$('pTitle').value=p.title||'';$('pSubtitle').value=p.subtitle||'';$('pDescription').value=p.description||'';$('pTech').value=(p.technologies||[]).join(', ');$('pResults').value=(p.results||[]).join('\n');$('pGithub').value=p.github||'';$('pDemo').value=p.demo||'';$('pImage').value=p.image||''}window.removeProject=async id=>{if(!confirm('Delete this project permanently?'))return;const {error}=await supabaseClient.from('projects').delete().eq('id',id);if(error)alert(error.message);else loadProjects()};$('addBtn').onclick=()=>{editingId=null;$('modalEyebrow').textContent='NEW PROJECT';$('modalTitle').textContent='Add project';['pTitle','pSubtitle','pDescription','pTech','pResults','pGithub','pDemo','pImage'].forEach(id=>$(id).value='');open()};function open(){$('modal').classList.remove('hidden');document.body.style.overflow='hidden';$('pTitle').focus()}function close(){$('modal').classList.add('hidden');document.body.style.overflow='';$('saveError').textContent=''}$('closeBtn').onclick=close;$('cancelBtn').onclick=close;$('modal').onclick=e=>{if(e.target.id==='modal')close()};$('saveBtn').onclick=async()=>{const title=$('pTitle').value.trim();if(!title){$('saveError').textContent='Project title is required.';return}$('saveError').textContent='';const payload={title,subtitle:$('pSubtitle').value.trim(),description:$('pDescription').value.trim(),technologies:$('pTech').value.split(',').map(x=>x.trim()).filter(Boolean),results:$('pResults').value.split('\n').map(x=>x.trim()).filter(Boolean),github:$('pGithub').value.trim(),demo:$('pDemo').value.trim(),image:$('pImage').value.trim()};let r;if(editingId)r=await supabaseClient.from('projects').update(payload).eq('id',editingId);else{const {count}=await supabaseClient.from('projects').select('*',{count:'exact',head:true});payload.sort_order=count||0;r=await supabaseClient.from('projects').insert(payload)}if(r.error)$('saveError').textContent=r.error.message;else{close();loadProjects()}};
$('logoutBtn').onclick=async()=>{await supabaseClient.auth.signOut();location.reload()};$('loginBtn').onclick=async()=>{$('loginError').textContent='';const {error}=await supabaseClient.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)$('loginError').textContent=error.message;else location.reload()};function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}boot();
